using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UrlShortner.Models
{
    public class UserModel
    {
        public UserModel(string name, string id)
        {
            this.Name = name;
            this.ID = id;
        }

        public UserModel(string name)
        {
            this.Name = name;
            this.ID = "autogeneratedid"; // TODO: implement
        }

        public string Name { get; private set; }

        public string ID { get; private set; }

    }
}